### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mike-wendt** [rapidsai/pygdf#299]
The README is out of date since the launch and with the changes made for the refactoring the instructions need to be updated as well

## TODO

- [x]  Change all references of pygdf to cudf
- [x]  Update build instructions to include building libgdf from the same repository and cudf
- [x]  Replace GoAi references and images with RAPIDS and link to new RAPIDS site

**Comment by mike-wendt** [comment]
Completed and in `cudf` branch
